# Generated by Django 4.0.3 on 2022-04-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='isPublished',
            field=models.BooleanField(default=False),
        ),
    ]
